name: KMP Build and Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Run Android tests
        run: ./gradlew :composeApp:testDebugUnitTest
        
      - name: Build Android APK
        run: ./gradlew :composeApp:assembleDebug
        
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/debug/*.apk

  build-kmp-framework:
    name: Build KMP Shared Framework
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Compile KMP shared code
        run: ./gradlew :composeApp:compileKotlinIosSimulatorArm64
        
      - name: Generate SQLDelight interfaces
        run: ./gradlew :composeApp:generateCommonMainAppDatabaseInterface
