name: KMP Build and Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run Android tests
      run: ./gradlew testDebugUnitTest
      
    - name: Build Android APK
      run: ./gradlew assembleDebug
      
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: composeApp/build/outputs/apk/debug/*.apk

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run iOS tests
      run: ./gradlew iosSimulatorArm64Test
      
    - name: Build iOS Framework
      run: ./gradlew linkDebugFrameworkIosSimulatorArm64
      
    - name: Generate Xcode project
      run: |
        cd iosApp
        # Listar simuladores disponibles para debug
        xcrun simctl list devices available
        # Compilar para cualquier simulador disponible
        xcodebuild -project iosApp.xcodeproj \
          -scheme iosApp \
          -destination 'generic/platform=iOS Simulator' \
          -configuration Debug \
          clean build \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE=""
          
    - name: Upload iOS App
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: ios-app
        path: iosApp/build/Build/Products/Debug-iphonesimulator/*.app
